version: "3.9"
services:
  frontend:
    container_name: frontend
    image: node:lts
    working_dir: /app/project
    entrypoint: ["npm", "run", "dev"]
    ports:
      - 8000:8000
    networks:
      - frontend-network
    volumes:
      - ./:/app/project
networks:
  frontend-network: