version: "3.9"
services:
  nestjs_fe:
    container_name: nestjs_fe
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - 8000:8080
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true